import type { CuratedBundle } from "../src/lib/engine/schemas";

export const seedCuratedBundles: CuratedBundle[] = [
  {
    title: "The Coffee Ritual",
    theme: "Slow coffee mornings",
    rationale: "For someone who treats coffee as a ceremony, not caffeine delivery.",
    estTotal: "$45–60",
    priceBand: "under-75",
    approved: true,
    sortWeight: 100,
    items: [
      { name: "Ceramic pour-over dripper set", description: "One-cup ceramic dripper with matching mug.", why: "Turns the morning cup into a ritual.", estPriceRange: "$18–25", searchQuery: "ceramic pour over coffee dripper set", tags: ["coffee", "home"] },
      { name: "Single-origin coffee sampler", description: "Three small bags from different regions.", why: "Lets them taste their way around the world.", estPriceRange: "$15–20", searchQuery: "single origin coffee sampler gift", tags: ["coffee", "food"] },
      { name: "Gooseneck pouring kettle", description: "Small stovetop kettle with precision spout.", why: "The tool that makes pour-over actually work.", estPriceRange: "$20–30", searchQuery: "gooseneck pour over kettle stovetop", tags: ["coffee", "kitchen"] },
    ],
  },
  {
    title: "The Cozy Reader",
    theme: "A perfect reading night in",
    rationale: "Everything a book lover needs to disappear for an evening.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: 90,
    items: [
      { name: "Rechargeable book light", description: "Clip-on warm-light lamp for reading in bed.", why: "Reading after everyone's asleep, guilt-free.", estPriceRange: "$12–18", searchQuery: "rechargeable clip on book reading light warm", tags: ["reading", "gadgets"] },
      { name: "Herbal tea gift tin", description: "Caffeine-free evening blends in a keepsake tin.", why: "The right companion for a long chapter.", estPriceRange: "$14–20", searchQuery: "herbal tea sampler gift tin", tags: ["tea", "food"] },
      { name: "Chunky knit throw blanket", description: "Soft oversized blanket for the reading chair.", why: "Cozy is a requirement, not a luxury.", estPriceRange: "$25–35", searchQuery: "chunky knit throw blanket soft", tags: ["home", "cozy"] },
    ],
  },
  {
    title: "New Parent Survival Kit",
    theme: "Comfort for exhausted new parents",
    rationale: "Gifts for the parents, not the baby — they need it more.",
    estTotal: "$50–70",
    priceBand: "under-75",
    approved: true,
    sortWeight: 80,
    items: [
      { name: "Insulated self-heating mug", description: "Temperature-holding mug for forgotten coffees.", why: "Every new parent drinks cold coffee. Not anymore.", estPriceRange: "$20–30", searchQuery: "temperature control insulated smart mug", tags: ["parents", "gadgets"] },
      { name: "Silk sleep eye mask", description: "Blackout silk mask for daytime naps.", why: "Sleep is the most precious gift now.", estPriceRange: "$12–18", searchQuery: "silk sleep eye mask blackout", tags: ["sleep", "selfcare"] },
      { name: "One-handed snack box", description: "Assorted eat-with-one-hand snacks.", why: "The other hand is holding a baby.", estPriceRange: "$18–25", searchQuery: "healthy snack box gift assortment", tags: ["food", "parents"] },
    ],
  },
  {
    title: "Desk Upgrade, Under $50",
    theme: "Office Secret Santa that doesn't feel generic",
    rationale: "Small desk luxuries that colleagues actually keep.",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: 70,
    items: [
      { name: "Desktop mini plant kit", description: "Low-maintenance succulent in a ceramic pot.", why: "A living thing that survives office lighting.", estPriceRange: "$12–16", searchQuery: "desk succulent plant ceramic pot kit", tags: ["office", "plants"] },
      { name: "Magnetic cable organizer", description: "Silicone magnetic ties that end cable chaos.", why: "Solves a daily annoyance they'd never fix themselves.", estPriceRange: "$8–12", searchQuery: "magnetic cable organizer desk silicone", tags: ["office", "gadgets"] },
      { name: "Premium gel pen set", description: "Smooth-writing pens in a gift case.", why: "People who love good pens really love good pens.", estPriceRange: "$14–20", searchQuery: "premium gel pen gift set smooth", tags: ["office", "stationery"] },
    ],
  },
  {
    title: "The Home Chef's Edge",
    theme: "Level up a keen cook's kitchen",
    rationale: "Sharp, useful upgrades — no gimmick gadgets.",
    estTotal: "$55–75",
    priceBand: "under-75",
    approved: true,
    sortWeight: 60,
    items: [
      { name: "Flaky finishing salt", description: "Sea salt flakes in a wooden serving box.", why: "The 'restaurant secret' every cook appreciates.", estPriceRange: "$10–15", searchQuery: "maldon flaky sea salt gift box", tags: ["cooking", "food"] },
      { name: "Cast iron mini skillet", description: "Pre-seasoned skillet for single servings.", why: "Perfect for the one-pan cookie they deserve.", estPriceRange: "$15–22", searchQuery: "mini cast iron skillet pre seasoned", tags: ["cooking", "kitchen"] },
      { name: "Digital instant-read thermometer", description: "Fast probe thermometer for meat and baking.", why: "The single biggest cooking accuracy upgrade.", estPriceRange: "$18–28", searchQuery: "instant read digital meat thermometer", tags: ["cooking", "gadgets"] },
    ],
  },
  {
    title: "Garden Therapy",
    theme: "Turning a stressful week into dirt and sunshine",
    rationale: "For someone who finds peace with their hands in soil.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: 55,
    items: [
      { name: "Ergonomic garden tool set", description: "Trowel, hand fork, and pruner with soft-grip handles.", why: "The everyday tools that make garden time actually comfortable.", estPriceRange: "$18–25", searchQuery: "ergonomic garden hand tool set soft grip", tags: ["gardening", "outdoors"] },
      { name: "Seed starter kit", description: "Compact indoor kit for starting herbs or flowers from seed.", why: "A small project that rewards patience with something living.", estPriceRange: "$12–18", searchQuery: "indoor seed starter kit herbs", tags: ["gardening", "home"] },
      { name: "Canvas gardening gloves", description: "Breathable gloves sized for real garden work.", why: "Protects the hands that do all the good work.", estPriceRange: "$10–14", searchQuery: "canvas gardening gloves durable", tags: ["gardening", "outdoors"] },
    ],
  },
  {
    title: "Fresh Start Fitness",
    theme: "For someone building a home workout habit",
    rationale: "Low-clutter gear for someone starting to move more at home.",
    estTotal: "$45–60",
    priceBand: "under-75",
    approved: true,
    sortWeight: 50,
    items: [
      { name: "Resistance band set", description: "Set of 5 bands in graduated resistance levels with a carry bag.", why: "A full home gym that fits in a drawer.", estPriceRange: "$15–20", searchQuery: "resistance bands set with bag graduated", tags: ["fitness", "home"] },
      { name: "Foam roller", description: "High-density roller for post-workout recovery.", why: "The unglamorous tool that actually prevents soreness.", estPriceRange: "$15–22", searchQuery: "high density foam roller recovery", tags: ["fitness", "recovery"] },
      { name: "Moisture-wicking gym towel set", description: "Quick-dry towels sized for gym bags.", why: "Small, useful, and always needed more than you think.", estPriceRange: "$10–15", searchQuery: "quick dry gym towel set", tags: ["fitness", "gym"] },
    ],
  },
  {
    title: "Level Up Night",
    theme: "A proper gaming setup upgrade",
    rationale: "For someone who spends serious hours at the console or PC.",
    estTotal: "$50–70",
    priceBand: "under-75",
    approved: true,
    sortWeight: 45,
    items: [
      { name: "RGB mouse pad with wrist rest", description: "Extended desk mat with cushioned wrist support.", why: "Comfort for the marathon sessions they already have planned.", estPriceRange: "$18–25", searchQuery: "extended rgb gaming mouse pad wrist rest", tags: ["gaming", "desk"] },
      { name: "Headset stand", description: "Weighted stand that keeps a headset off the desk.", why: "Small upgrade, instantly tidier setup.", estPriceRange: "$14–20", searchQuery: "gaming headset stand weighted", tags: ["gaming", "desk"] },
      { name: "Snack and drink desk organizer", description: "Compact caddy for snacks, drink, and controller.", why: "Keeps the essentials in arm's reach mid-match.", estPriceRange: "$15–22", searchQuery: "gaming desk snack drink organizer caddy", tags: ["gaming", "desk"] },
    ],
  },
  {
    title: "Wanderer's Carry-On",
    theme: "Small upgrades for someone always packing a bag",
    rationale: "The unglamorous gear that makes travel days smoother.",
    estTotal: "$45–65",
    priceBand: "under-75",
    approved: true,
    sortWeight: 40,
    items: [
      { name: "Packing cube set", description: "Compression cubes in 3 sizes for organized packing.", why: "Turns a chaotic suitcase into a system.", estPriceRange: "$18–25", searchQuery: "packing cubes set compression travel", tags: ["travel", "organization"] },
      { name: "Portable luggage scale", description: "Digital hook scale to avoid overweight fees at check-in.", why: "Solves the one thing that ruins the start of every trip.", estPriceRange: "$10–15", searchQuery: "digital luggage scale portable hook", tags: ["travel", "gadgets"] },
      { name: "Travel-size toiletry bottle set", description: "Leak-proof silicone bottles for liquids.", why: "TSA-friendly and actually reusable.", estPriceRange: "$12–18", searchQuery: "silicone travel toiletry bottles leak proof set", tags: ["travel", "essentials"] },
    ],
  },
  {
    title: "Spoiled Rotten (the Dog)",
    theme: "Because the dog deserves presents too",
    rationale: "For the friend whose dog is basically a family member.",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: 35,
    items: [
      { name: "Durable rubber chew toy", description: "Tough treat-stuffable rubber toy for enthusiastic chewers.", why: "Built to survive a genuinely determined dog.", estPriceRange: "$10–15", searchQuery: "durable rubber treat stuffable dog chew toy", tags: ["pets", "dog"] },
      { name: "Orthopedic dog bed", description: "Memory-foam bed sized for medium dogs.", why: "A proper upgrade from the flattened old cushion.", estPriceRange: "$18–28", searchQuery: "orthopedic memory foam dog bed medium", tags: ["pets", "dog"] },
      { name: "Gourmet dog treat variety box", description: "Assorted natural treats in small-batch flavors.", why: "The good stuff, not the bargain-bin biscuits.", estPriceRange: "$12–18", searchQuery: "gourmet natural dog treat variety box", tags: ["pets", "dog"] },
    ],
  },
  {
    title: "The Cat Whisperer's Kit",
    theme: "For the person owned by their cat",
    rationale: "Enrichment gifts that actually get used, not ignored.",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: 30,
    items: [
      { name: "Interactive puzzle feeder", description: "Slow-feed puzzle toy that rewards a cat for working at it.", why: "Mental stimulation that also slows down a fast eater.", estPriceRange: "$12–18", searchQuery: "interactive cat puzzle slow feeder toy", tags: ["pets", "cat"] },
      { name: "Wall-mounted cat shelf", description: "Carpeted perch shelf for climbing and lounging.", why: "Cats want vertical space more than almost anything.", estPriceRange: "$16–24", searchQuery: "wall mounted cat shelf perch carpeted", tags: ["pets", "cat"] },
      { name: "Silvervine and catnip toy set", description: "Assorted plush toys infused with silvervine and catnip.", why: "The rare gift that gets an immediate, delighted reaction.", estPriceRange: "$10–14", searchQuery: "silvervine catnip toy set cat", tags: ["pets", "cat"] },
    ],
  },
  {
    title: "Paint & Unwind",
    theme: "A creative evening, no talent required",
    rationale: "Low-pressure art supplies for someone who wants to make something with their hands.",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: 25,
    items: [
      { name: "Watercolor paint set with pad", description: "Beginner-friendly paints, brushes, and a bound paper pad.", why: "Everything needed to start, nothing to figure out first.", estPriceRange: "$16–22", searchQuery: "beginner watercolor paint set with paper pad", tags: ["art", "crafts"] },
      { name: "Guided sketchbook", description: "Journal with prompts and light guidance for drawing practice.", why: "Removes the 'blank page' problem entirely.", estPriceRange: "$10–15", searchQuery: "guided sketchbook drawing prompts journal", tags: ["art", "journaling"] },
      { name: "Washi tape and sticker set", description: "Decorative tape and stickers for journaling or scrapbooking.", why: "Instant, low-effort creative satisfaction.", estPriceRange: "$8–12", searchQuery: "washi tape sticker set journaling", tags: ["art", "crafts"] },
    ],
  },
  {
    title: "Vinyl Nights",
    theme: "For someone who still buys records",
    rationale: "Small upgrades for an analog music habit.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: 20,
    items: [
      { name: "Record cleaning kit", description: "Anti-static brush and cleaning fluid for vinyl care.", why: "Keeps every record sounding as good as day one.", estPriceRange: "$14–20", searchQuery: "vinyl record cleaning kit anti static brush", tags: ["music", "vinyl"] },
      { name: "Record storage crate", description: "Wooden crate sized to hold and display LPs upright.", why: "A collection deserves to look like one.", estPriceRange: "$18–25", searchQuery: "wooden vinyl record storage crate", tags: ["music", "home"] },
      { name: "Classic album on vinyl", description: "A widely loved album pressed on 180g vinyl.", why: "A genuinely great excuse to add to the shelf.", estPriceRange: "$20–28", searchQuery: "classic album 180g vinyl record", tags: ["music", "vinyl"] },
    ],
  },
  {
    title: "The Spa Night In",
    theme: "Restaurant-quality pampering, at home",
    rationale: "For someone who needs permission to do absolutely nothing productive.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: 15,
    items: [
      { name: "Weighted eye mask", description: "Lavender-scented mask with gentle weighted pressure.", why: "Instantly signals 'nap time' to an overworked brain.", estPriceRange: "$14–20", searchQuery: "weighted lavender eye mask spa", tags: ["selfcare", "relaxation"] },
      { name: "Bath soak and bomb set", description: "Assorted mineral soaks and bath bombs in calming scents.", why: "A full evening's worth of unwinding in one box.", estPriceRange: "$14–20", searchQuery: "bath bomb soak gift set calming scents", tags: ["selfcare", "bath"] },
      { name: "Facial roller and gua sha set", description: "Cool stone roller and gua sha tool with pouch.", why: "The 10-minute ritual that feels like a mini facial.", estPriceRange: "$12–18", searchQuery: "facial roller gua sha stone set", tags: ["selfcare", "beauty"] },
    ],
  },
  {
    title: "Basecamp Ready",
    theme: "For weekend trips into the woods",
    rationale: "Practical gear for someone who actually uses it, not just Instagrams it.",
    estTotal: "$50–70",
    priceBand: "under-75",
    approved: true,
    sortWeight: 10,
    items: [
      { name: "Compact camping hammock", description: "Packable nylon hammock with tree straps included.", why: "The best seat at any campsite, folds to fit a pocket.", estPriceRange: "$20–28", searchQuery: "compact camping hammock with tree straps", tags: ["outdoors", "camping"] },
      { name: "Rechargeable lantern", description: "Collapsible LED lantern with USB charging.", why: "No batteries to forget, no flame to worry about.", estPriceRange: "$15–22", searchQuery: "rechargeable collapsible led camping lantern", tags: ["outdoors", "camping"] },
      { name: "Multi-tool with sheath", description: "Compact multi-tool covering the basics: knife, pliers, screwdriver.", why: "The tool they'll reach for on every trip after this one.", estPriceRange: "$16–24", searchQuery: "compact multi tool with sheath camping", tags: ["outdoors", "gear"] },
    ],
  },
  {
    title: "Grandparent Favorites",
    theme: "Timeless gifts for someone who has everything",
    rationale: "Warm, practical gifts that skip the gimmicks entirely.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: 5,
    items: [
      { name: "Photo album with caption prompts", description: "Bound album pre-filled with prompts for captions.", why: "A gift that becomes more valuable with every year.", estPriceRange: "$16–22", searchQuery: "photo album gift book with caption prompts", tags: ["family", "keepsake"] },
      { name: "Large-print puzzle book set", description: "Crosswords and word searches in easy-to-read print.", why: "Genuinely enjoyable, not just easy to shop for.", estPriceRange: "$10–15", searchQuery: "large print crossword word search puzzle book set", tags: ["family", "games"] },
      { name: "Soft cardigan or wrap", description: "Lightweight knit wrap for cool evenings.", why: "Comfort that gets worn constantly, not put in a drawer.", estPriceRange: "$18–25", searchQuery: "soft lightweight knit wrap cardigan gift", tags: ["family", "comfort"] },
    ],
  },
  {
    title: "Teen Approved",
    theme: "Gifts a teenager will actually use",
    rationale: "Genuinely useful picks, not obviously 'from an adult.'",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: 0,
    items: [
      { name: "Portable Bluetooth speaker", description: "Compact clip-on speaker with strong bass for the size.", why: "Music anywhere, without asking to borrow a phone charger for it.", estPriceRange: "$18–25", searchQuery: "compact clip on bluetooth speaker portable", tags: ["tech", "music"] },
      { name: "LED strip lights with remote", description: "Color-changing lights for a room glow-up.", why: "An instant room upgrade, zero effort required.", estPriceRange: "$10–15", searchQuery: "led strip lights remote color changing room", tags: ["tech", "home"] },
      { name: "Phone camera lens kit", description: "Clip-on wide and macro lenses for smartphone photography.", why: "Levels up every photo they were already taking.", estPriceRange: "$10–14", searchQuery: "phone camera lens kit clip on wide macro", tags: ["tech", "photography"] },
    ],
  },
  {
    title: "Cozy Christmas Morning",
    theme: "Building the perfect holiday morning",
    rationale: "The small touches that make Christmas morning feel special.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: -5,
    items: [
      { name: "Matching family pajama set", description: "Soft cotton pajamas in a classic holiday print.", why: "The photo everyone will actually want to take.", estPriceRange: "$18–25", searchQuery: "matching family christmas pajama set cotton", tags: ["holiday", "home"] },
      { name: "Hot cocoa and marshmallow gift set", description: "Rich cocoa mix with toppings in a festive tin.", why: "The smell alone makes it feel like the holidays.", estPriceRange: "$12–18", searchQuery: "hot cocoa marshmallow gift set tin", tags: ["holiday", "food"] },
      { name: "Personalized stocking", description: "Knit stocking that can be embroidered with a name.", why: "A tradition that starts with this one gift.", estPriceRange: "$14–20", searchQuery: "personalized knit christmas stocking", tags: ["holiday", "keepsake"] },
    ],
  },
  {
    title: "Journal & Reflect",
    theme: "For someone starting a new chapter",
    rationale: "For a fresh start, breakup recovery, new job, or just a new year.",
    estTotal: "$35–50",
    priceBand: "under-50",
    approved: true,
    sortWeight: -10,
    items: [
      { name: "Guided reflection journal", description: "Structured journal with prompts for goals and gratitude.", why: "Turns vague good intentions into an actual habit.", estPriceRange: "$14–20", searchQuery: "guided reflection journal goals gratitude prompts", tags: ["selfcare", "journaling"] },
      { name: "Quality gel pen", description: "Smooth-writing pen that makes journaling feel nicer.", why: "Small detail, surprisingly motivating.", estPriceRange: "$12–18", searchQuery: "smooth writing gel pen gift", tags: ["journaling", "stationery"] },
      { name: "Affirmation card deck", description: "Deck of daily prompt or affirmation cards.", why: "A tiny, positive ritual to start the day.", estPriceRange: "$10–14", searchQuery: "daily affirmation card deck gift", tags: ["selfcare", "mindfulness"] },
    ],
  },
  {
    title: "Baker's Dozen",
    theme: "For someone who bakes for fun, not necessity",
    rationale: "The kind of kitchen extras that make baking easier, not just cuter.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: -15,
    items: [
      { name: "Silicone baking mat set", description: "Non-stick reusable mats sized for standard baking sheets.", why: "Ends parchment paper waste for good.", estPriceRange: "$12–18", searchQuery: "silicone baking mat set non stick reusable", tags: ["baking", "kitchen"] },
      { name: "Decorating piping tip set", description: "Stainless steel tips with coupler and storage case.", why: "The detail work that turns 'homemade' into 'wow.'", estPriceRange: "$14–20", searchQuery: "cake decorating piping tip set stainless steel", tags: ["baking", "kitchen"] },
      { name: "Digital kitchen scale", description: "Precision scale for accurate baking measurements.", why: "The single upgrade that fixes inconsistent bakes.", estPriceRange: "$14–20", searchQuery: "digital kitchen scale precision baking", tags: ["baking", "gadgets"] },
    ],
  },
  {
    title: "Marathon Mindset",
    theme: "For the runner training for their next race",
    rationale: "Practical gear for someone logging serious miles.",
    estTotal: "$45–65",
    priceBand: "under-75",
    approved: true,
    sortWeight: -20,
    items: [
      { name: "Running belt with phone pocket", description: "Adjustable waist belt with pocket for phone and keys.", why: "Solves the 'where do I even put my phone' problem.", estPriceRange: "$14–20", searchQuery: "running waist belt phone pocket adjustable", tags: ["running", "fitness"] },
      { name: "Moisture-wicking running socks", description: "Blister-resistant socks built for long distances.", why: "The unglamorous gear that actually prevents injury.", estPriceRange: "$12–18", searchQuery: "moisture wicking running socks blister resistant", tags: ["running", "gear"] },
      { name: "Handheld water bottle with strap", description: "Ergonomic bottle with adjustable hand strap.", why: "Hydration without breaking stride.", estPriceRange: "$16–22", searchQuery: "handheld running water bottle strap ergonomic", tags: ["running", "fitness"] },
    ],
  },
  {
    title: "Yoga Reset",
    theme: "A calmer morning routine, mat included",
    rationale: "For someone building a home practice, not a studio membership.",
    estTotal: "$45–60",
    priceBand: "under-75",
    approved: true,
    sortWeight: -25,
    items: [
      { name: "Non-slip yoga mat", description: "Extra-thick mat with alignment guide lines.", why: "Comfort and guidance for building consistent form.", estPriceRange: "$20–28", searchQuery: "non slip yoga mat alignment lines thick", tags: ["yoga", "fitness"] },
      { name: "Cork yoga blocks (pair)", description: "Sustainable cork blocks for support and flexibility work.", why: "Makes poses accessible long before flexibility catches up.", estPriceRange: "$14–20", searchQuery: "cork yoga blocks pair sustainable", tags: ["yoga", "fitness"] },
      { name: "Meditation cushion", description: "Round zafu cushion for floor sitting comfort.", why: "Turns 'I should meditate' into 'I actually can, comfortably.'", estPriceRange: "$16–22", searchQuery: "round meditation zafu cushion floor", tags: ["yoga", "mindfulness"] },
    ],
  },
  {
    title: "Board Game Night Host",
    theme: "For the friend who always hosts game night",
    rationale: "Gifts for the person who keeps the group together.",
    estTotal: "$40–55",
    priceBand: "under-75",
    approved: true,
    sortWeight: -30,
    items: [
      { name: "Highly-rated strategy board game", description: "A well-reviewed modern board game for 2-5 players.", why: "Fresh material for a group that's beaten every game they own.", estPriceRange: "$25–35", searchQuery: "highly rated modern strategy board game 2-5 players", tags: ["games", "social"] },
      { name: "Card game organizer case", description: "Compartmentalized case for sorting game pieces and cards.", why: "Ends the 'where's the tiny piece' hunt before every game.", estPriceRange: "$10–15", searchQuery: "board game card organizer storage case", tags: ["games", "organization"] },
      { name: "Snack and dip party platter set", description: "Divided serving tray for game-night snacks.", why: "Keeps hands busy and the table from turning into chaos.", estPriceRange: "$12–18", searchQuery: "divided party snack platter tray", tags: ["games", "food"] },
    ],
  },
];
